### ISSUE TITLE
Вопросы к эффектам

### ISSUE THREAD

**Issue by 80Stepko08** [SlingMaster/WiFiLamp#1]
Посмотрел ваши новые эффекты и меня появились вопросы.
Например эффект "Украина" : зачем вам 32х битный массив, если герб можно и bool ами сделать.
Посмотрел демо вашого эффекта в Soulmate IDE и вообще не понял эффект.
Могу оптимизировать, если хотите. Если че я в Телеграмме @S_7_E_P_4_N

**Comment by SlingMaster** [comment]
да можно и через  bool , там много чего можно оптимизировать
это второй эффект на C++ и третья попытка на C++ до этого его в глаза его не видел  
сделано так что первым пришло в голову через bool с ходу не получилось уже не помню почему
если есть желание можете оптимизировать
насчет эффекта в Soulmate IDE ничего не могу сказать
в ревальности при старте эффекта появляется герб потом рисуется флаг и в процессе иметируется волна
в реальности выглядит не плохо
